package com.springcat.ide.ui.screen

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.FilterChip
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import com.springcat.ide.core.keystore.DistinguishedName
import com.springcat.ide.core.keystore.GeneratedKeystore
import com.springcat.ide.core.keystore.KeyAlgorithm
import com.springcat.ide.core.keystore.KeystoreManager
import com.springcat.ide.core.keystore.KeystoreRequest

@OptIn(ExperimentalLayoutApi::class)
@Composable
fun KeystoreScreen(onBack: () -> Unit) {
    val context = LocalContext.current
    val manager = remember { KeystoreManager() }

    var alias by remember { mutableStateOf("upload") }
    var storePassword by remember { mutableStateOf("") }
    var keyPassword by remember { mutableStateOf("") }
    var commonName by remember { mutableStateOf("") }
    var organization by remember { mutableStateOf("") }
    var country by remember { mutableStateOf("") }
    var validity by remember { mutableStateOf("25") }
    var algorithm by remember { mutableStateOf(KeyAlgorithm.RSA) }
    var storeType by remember { mutableStateOf("PKCS12") }

    var generated by remember { mutableStateOf<GeneratedKeystore?>(null) }
    var status by remember { mutableStateOf<String?>(null) }

    // SAF launchers for exporting the generated artefacts.
    val saveKeystore = rememberLauncherForActivityResult(
        ActivityResultContracts.CreateDocument("application/octet-stream"),
    ) { uri ->
        val g = generated ?: return@rememberLauncherForActivityResult
        if (uri != null) runCatching {
            context.contentResolver.openOutputStream(uri)?.use { out ->
                manager.write(g.keyStore, out, storePassword.toCharArray())
            }
        }.onSuccess { status = "Keystore saved." }.onFailure { status = "Save failed: ${it.message}" }
    }

    val saveCert = rememberLauncherForActivityResult(
        ActivityResultContracts.CreateDocument("application/x-pem-file"),
    ) { uri ->
        val g = generated ?: return@rememberLauncherForActivityResult
        if (uri != null) runCatching {
            context.contentResolver.openOutputStream(uri)?.use { out ->
                manager.exportCertificatePem(g.certificate, out)
            }
        }.onSuccess { status = "Certificate exported." }.onFailure { status = "Export failed: ${it.message}" }
    }

    Scaffold(topBar = { ScreenHeader(title = "Keystore & Certificate", onBack = onBack) }) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp),
        ) {
            field("Key alias", alias) { alias = it }
            field("Keystore password", storePassword, isPassword = true) { storePassword = it }
            field("Key password", keyPassword, isPassword = true) { keyPassword = it }
            field("Common Name (CN)", commonName) { commonName = it }
            field("Organization (O)", organization) { organization = it }
            field("Country (C, 2 letters)", country) { country = it }
            field("Validity (years)", validity) { validity = it.filter(Char::isDigit) }

            Text("Algorithm", style = MaterialTheme.typography.labelLarge)
            FlowRow(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                KeyAlgorithm.entries.forEach { a ->
                    FilterChip(
                        selected = algorithm == a,
                        onClick = { algorithm = a },
                        label = { Text(chipLabel(a)) },
                    )
                }
            }

            Text("Store type", style = MaterialTheme.typography.labelLarge)
            FlowRow(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                listOf("PKCS12", "JKS").forEach { t ->
                    FilterChip(
                        selected = storeType == t,
                        onClick = { storeType = t },
                        label = { Text(t) },
                    )
                }
            }

            Button(
                onClick = {
                    status = null
                    val result = runCatching {
                        manager.generate(
                            KeystoreRequest(
                                alias = alias,
                                keystorePassword = storePassword.toCharArray(),
                                keyPassword = keyPassword.ifBlank { storePassword }.toCharArray(),
                                dn = DistinguishedName(
                                    commonName = commonName,
                                    organization = organization,
                                    country = country,
                                ),
                                validityYears = validity.toIntOrNull() ?: 25,
                                algorithm = algorithm,
                                storeType = storeType,
                            ),
                        )
                    }
                    result
                        .onSuccess {
                            generated = it
                            status = "Generated. SHA-256 fingerprint:\n${fingerprint(it)}"
                        }
                        .onFailure { status = "Error: ${it.message}" }
                },
                modifier = Modifier.fillMaxWidth(),
                enabled = commonName.isNotBlank() && storePassword.length >= 6,
            ) { Text("Generate keystore") }

            generated?.let {
                Card(colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)) {
                    Column(Modifier.fillMaxWidth().padding(16.dp)) {
                        Text("Ready to export", style = MaterialTheme.typography.titleMedium)
                        Spacer(Modifier.height(8.dp))
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            Button(onClick = {
                                val ext = if (storeType == "PKCS12") "p12" else "jks"
                                saveKeystore.launch("$alias.$ext")
                            }) { Text("Save keystore") }
                            OutlinedButton(onClick = { saveCert.launch("$alias.pem") }) {
                                Text("Export cert")
                            }
                        }
                    }
                }
            }

            status?.let {
                Text(
                    it,
                    style = MaterialTheme.typography.bodySmall,
                    fontFamily = FontFamily.Monospace,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
    }
}

private fun chipLabel(a: KeyAlgorithm): String = when (a) {
    KeyAlgorithm.RSA -> "RSA 2048"
    KeyAlgorithm.RSA_4096 -> "RSA 4096"
    KeyAlgorithm.EC -> "EC P-256"
}

private fun fingerprint(g: GeneratedKeystore): String {
    val md = java.security.MessageDigest.getInstance("SHA-256")
    return md.digest(g.certificate.encoded).joinToString(":") { "%02X".format(it) }
}

@Composable
private fun field(
    label: String,
    value: String,
    isPassword: Boolean = false,
    onChange: (String) -> Unit,
) {
    OutlinedTextField(
        value = value,
        onValueChange = onChange,
        label = { Text(label) },
        singleLine = true,
        modifier = Modifier.fillMaxWidth(),
        visualTransformation = if (isPassword) PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None,
    )
}
