package com.example.keystoredecoder

import java.security.MessageDigest
import javax.crypto.EncryptedPrivateKeyInfo

/**
 * Decrypts private keys stored in a **JKS** keystore.
 *
 * JKS protects each private key with Sun's proprietary "JavaSoft
 * JDKKeyProtector" algorithm (OID 1.3.6.1.4.1.42.2.17.1.1), which no
 * security provider on Android implements. This is a faithful port of
 * `sun.security.provider.KeyProtector`:
 *
 * The protected blob is `salt(20) || encrypted || checkDigest(20)`. A
 * SHA-1 keystream is generated by repeatedly hashing
 * `password || previousDigest` (starting from the salt); the plaintext is
 * `encrypted XOR keystream`. Correctness is confirmed by checking that
 * `SHA-1(password || plaintext) == checkDigest`. The recovered plaintext is
 * a DER-encoded PKCS#8 `PrivateKeyInfo`.
 */
object JksKeyProtector {

    private const val SALT_LEN = 20
    private const val DIGEST_LEN = 20

    class WrongKeyPasswordException(message: String) : Exception(message)

    /**
     * @param protectedBlob the DER `EncryptedPrivateKeyInfo` stored in the JKS file.
     * @param password the key password (often the same as the store password).
     * @return the decrypted PKCS#8 `PrivateKeyInfo` DER bytes.
     * @throws WrongKeyPasswordException if the password does not match.
     */
    fun recover(protectedBlob: ByteArray, password: CharArray): ByteArray {
        // The stored blob wraps the actual protected bytes in an
        // EncryptedPrivateKeyInfo; pull out its encrypted-data octet string.
        val protectedKey = EncryptedPrivateKeyInfo(protectedBlob).encryptedData

        if (protectedKey.size < SALT_LEN + DIGEST_LEN) {
            throw WrongKeyPasswordException("Protected key too short")
        }

        val encrKeyLen = protectedKey.size - SALT_LEN - DIGEST_LEN
        var numRounds = encrKeyLen / DIGEST_LEN
        if (encrKeyLen % DIGEST_LEN != 0) numRounds++

        val encrKey = protectedKey.copyOfRange(SALT_LEN, SALT_LEN + encrKeyLen)
        val passwordBytes = passwordToBytes(password)

        val md = MessageDigest.getInstance("SHA-1")
        val xorKey = ByteArray(encrKeyLen)
        var digest = protectedKey.copyOfRange(0, SALT_LEN) // start from salt
        var offset = 0
        repeat(numRounds) {
            md.update(passwordBytes)
            md.update(digest)
            digest = md.digest()
            md.reset()
            val n = minOf(DIGEST_LEN, encrKeyLen - offset)
            System.arraycopy(digest, 0, xorKey, offset, n)
            offset += DIGEST_LEN
        }

        val plainKey = ByteArray(encrKeyLen)
        for (i in 0 until encrKeyLen) {
            plainKey[i] = (encrKey[i].toInt() xor xorKey[i].toInt()).toByte()
        }

        // Integrity check: SHA-1(password || plainKey) must equal the trailing digest.
        md.update(passwordBytes)
        md.update(plainKey)
        val check = md.digest()
        md.reset()
        for (i in 0 until DIGEST_LEN) {
            if (check[i] != protectedKey[SALT_LEN + encrKeyLen + i]) {
                throw WrongKeyPasswordException(
                    "Cannot recover key: wrong password or corrupted entry."
                )
            }
        }
        return plainKey
    }

    /** Each char becomes two bytes, high byte first (as Sun's KeyProtector does). */
    private fun passwordToBytes(password: CharArray): ByteArray {
        val out = ByteArray(password.size * 2)
        for (i in password.indices) {
            out[i * 2] = (password[i].code ushr 8).toByte()
            out[i * 2 + 1] = password[i].code.toByte()
        }
        return out
    }
}
